from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column

from src.db import Base
from src.modules.helpers.models import TableInsertMeta


class User(Base, TableInsertMeta):
    __tablename__ = "users"

    username: Mapped[str] = mapped_column(String(30), nullable=False, index=True)

    # recommended email str length is 254
    email: Mapped[str] = mapped_column(String(254), nullable=False, index=True)
    hashed_pwd: Mapped[str] = mapped_column(String(), nullable=False)

    # `id` column will be indexed by default as it is the primary key
    # ℹ️ Here, we used init=False instead of default=None because `init=False` will be more accurate because id will be generated by the DB
    id: Mapped[int] = mapped_column(primary_key=True, init=False)
